improve（rds）:Adding different versions of submodules
terraform-alicloud-modules/terraform-alicloud-rds pull request #11
Opened 2019-12-25 08:17 UTC by Rich-yi

2019-12-26 03:02 UTC, xiaozhu36 requested changes

2019-12-26 03:02 UTC, xiaozhu36 commented on CHANGELOG.md
> ->>>>>>> inporve_rds
为啥要把上面的删掉

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.5-high-availability/variables.tf
> +variable "create_db_readonly_instance" {
readonly先不做

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.5-high-availability/variables.tf
> +variable "create_connection" {
connection不是已经改称allocation_public_connection 么

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = "cn-beijing"
默认值要置为“”

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = "myTestDB"
用一个random 产生一个随机的name

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = "20"
如果是数字，要写 type = number

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = "rds.mysql.s2.large"
实例规格不要给默认值

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = "myTestInstance"
这个也类似，用random产生一个随机的

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = true
bool类型要声明type= bool

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = "cn-beijing-h"
可用区也不要给默认值，不然region一变，zone就不能用了

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/mysql-5.7-enterprise/main.tf
> +  storage_type   = "cloud_ssd"
我理解不是所有的都是cloud_ssd吧

2019-12-26 03:02 UTC, xiaozhu36 commented on modules/postgre_sql-9.4-high-availability/main.tf
> +  storage_type   = "cloud_ssd"
有些不支持cloud_ssd

2019-12-26 11:26 UTC, xiaozhu36 requested changes

2019-12-26 11:26 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +  "121.43.18.0/24"]
这几个ip地址是从哪儿来的

2019-12-26 11:26 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +module "databases" {
这个地方没必要单独用一个module，直接跟上个module合并了就行

2019-12-26 11:26 UTC, xiaozhu36 commented on examples/postgre_sql/main.tf
> +  region               = "cn-beijing"
如果这个地方设置了region，那么上面也得设置一个provider，并指定对应的region，不然一旦环境变量的region不是北京，就会出错

2019-12-26 11:26 UTC, xiaozhu36 commented on examples/postgre_sql/main.tf
> +  vswitch_id           = data.alicloud_vpcs.default.vswitch_id
如果vswitchid是从vpcs的datasource中获取到的，那么对应的zoneId应该根据获取到的vswitchid和vsw的datasoure查出来vsw所在的zone，不然一旦vswitch的zone变了，跟zoneid中指定的不一致，就会报错

2019-12-26 11:26 UTC, xiaozhu36 commented on examples/postgre_sql/main.tf
>    log_retention_period = 7
这几个backup policy相关的参数，名称最好跟API中定义的保持一致吧：https://help.aliyun.com/document_detail/26276.html?spm=a2c4g.11174283.6.1599.6d854c22ctXDCk

2019-12-26 11:26 UTC, xiaozhu36 commented on modules/database/main.tf
> +  name          = "${lookup(var.databases[count.index], "name")}-${random_uuid.this.result}"
random返回的字段会很长，看下文档，然后根据name的长度限制对拼接后的字段进行截取

2019-12-26 11:26 UTC, xiaozhu36 commented on modules/database/variables.tf
>  }
下次提交代码前记得执行 terraform fmt 进行格式化

2019-12-26 11:26 UTC, xiaozhu36 commented on modules/mysql-5.5-high-availability/variables.tf
>  }
我理解engine和engine version这两个参数已经没用了吧
把variables中没有用到的参数都去掉吧

2019-12-26 11:26 UTC, xiaozhu36 commented on modules/mysql-5.5-high-availability/variables.tf
>  variable "vpc_security_group_ids" {
vpc_security_group_ids 改成 security_group_ids

2019-12-26 11:26 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/README.md
> +# Complete RDS example for MySQL
这个名称不可能都是 Comlete RDS examples把，要根据实际来，比如：mysql-5.6-enterprise - Alibaba Cloud Rds Terraform Module

2019-12-26 11:26 UTC, xiaozhu36 commented on modules/mysql-5.6-enterprise/variables.tf
> +  default     = "rds.mysql.s2.large"
这个也没改啊

2019-12-27 07:32 UTC, xiaozhu36 requested changes

2019-12-27 07:32 UTC, xiaozhu36 commented on README.md
> +# Alicloud RDS Instance Terraform Module
用 Alibaba Cloud

2019-12-27 07:32 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +  vpc_id = data.alicloud_vpcs.default.id
这个地方只使用 vpc id是不行的，不能确保module中使用的zoneid和vswitch所在的zoneid是一个，应该直接用获取到的vswitchid去查
```
data "alicloud_vswitches" "default" {
  ids = data.alicloud_vpcs.default.vpcs.0.vswitch_id
}

2019-12-27 07:32 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +  vswitch_id           = data.alicloud_vpcs.default.vswitch_id
这个example你运行了么？15行的写法肯定不对啊

2020-01-02 12:38 UTC, xiaozhu36 requested changes

2020-01-02 12:38 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +  region               = "cn-hangzhou"
用一个region变量来代替写死在两个地方

2020-01-02 12:38 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +  connection_prefix    = "testabc"
最好不要出现test字眼，用一个其他的字眼，比如development

2020-01-02 12:38 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +  instance_charge_type = "Postpaid"
有默认值的可以不用体现在example中

2020-01-02 12:38 UTC, xiaozhu36 commented on examples/mysql/main.tf
> +  instance_name        = "myTestDBInstance"
这个也是一样的，test

2020-01-03 12:39 UTC, xiaozhu36 requested changes

2020-01-03 12:39 UTC, xiaozhu36 commented on examples/sql_server/output.tf
> +output "this_database_accountprivilege" {
`this_database_accountprivilege` -> `this_database_account_privilege `

2020-01-03 12:39 UTC, xiaozhu36 commented on modules/database/variables.tf
>    default = true
上面的两个参数create_database 和 create_account有使用到么？

2020-01-03 12:39 UTC, xiaozhu36 commented on outputs.tf
>  locals {
这个地方定义这些 locals的作用是啥？不用了就去掉

2020-01-04 02:19 UTC, Rich-yi commented on modules/database/variables.tf
>    default = true
这两个在database module中使用到了

2020-01-04 08:09 UTC, xiaozhu36 requested changes

2020-01-04 08:09 UTC, xiaozhu36 commented on README.md
>    log_retention_period         = 7
日志备份的这几个参数应该不是最新的，我记得你在代码中已经改成和API一致的了

2020-01-04 08:09 UTC, xiaozhu36 commented on main.tf
> +  //log_backup           = var.log_backup
不用的代码就去掉吧

2020-01-04 08:09 UTC, xiaozhu36 commented on modules/mysql-5.5-high-availability/main.tf
> +  log_retention_period = var.log_backup_retention_period
这几个备份的参数也不对吧
另外，注意代码格式化

2020-01-04 08:09 UTC, xiaozhu36 commented on modules/mysql-5.6-high-availability/variables.tf
> +
多余的空格去掉吧

2020-01-04 08:09 UTC, xiaozhu36 commented on modules/database/main.tf
> +  name          = substr("${lookup(var.databases[count.index], "name")}-${random_uuid.this.result}",0 , 256)
这个name没必要使用random，本身就是一个列表，所以直接使用 lookup(var.databases[count.index], "name") 就行。

2020-01-04 08:09 UTC, xiaozhu36 commented on modules/mysql-5.7-basic/variables.tf
> +  description = "add databases"
这个描述改成 “A list mapping used to add multiple databases. Each item supports keys: `name`, `character_set` and `description`.”
其他module中的也都改下

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +  description = "Filter the results by charge type. Valid values: PrePaid and PostPaid. Default to PostPaid."
valid values应该是 Prepaid和Postpaid

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +  description = "A specified account name."
description = "Name of a new database account. It should be set when `create_account = true`."

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +  description = "add databases"
跟上面的一样

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +variable "vswitch_resource_group_id" {
我理解这个vswitch_resource_group_id应该不需要了

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +variable "vswitch_tags" {
如果去掉了vswitch的data source，vswitch_name_regex 和 vswitch_tags 都不需要了

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +  default     = []
这个module现在只支持一个rds instance的创建，所以应该是vswitch_id吧

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +variable "connection_list" {
connection_list 有用么？

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
>  variable "create_account" {
加一个description:  description = "Whether to create a new database account."

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
> +  description = "Adding databases"
description = "Whether to create multiple databases."

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
>  variable "log_backup" {
这个几个备份策略的参数没改

2020-01-04 08:09 UTC, xiaozhu36 commented on variables.tf
>    description = "List of VPC security groups to associate"
description = "List of VPC security group ids to associate with rds instance."

2020-01-04 08:09 UTC, xiaozhu36 commented on outputs.tf
> -output "this_db_instance_zone_id" {
zone_id 还是要输出出来的

2020-01-04 08:09 UTC, xiaozhu36 commented on outputs.tf
>  }
另外，database module中的那几个出参也是要在这个主module的outputs中输出的。

2020-01-04 08:34 UTC, Rich-yi commented on modules/mysql-5.5-high-availability/main.tf
> +  log_retention_period = var.log_backup_retention_period
因为在example中的字段需要与API保持一致但是resoucr支持的字段名不一样，所以sub module中对应的字段名不同

2020-01-04 08:47 UTC, Rich-yi commented on outputs.tf
>  }
已经是在主module中输出了

2020-01-06 07:48 UTC, xiaozhu36 approved these changes

2020-01-06 07:48 UTC, merged